[
    'https://rcmakelaars.nl/woningen/oorgat-104-edam/',
    'https://rcmakelaars.nl/woningen/tjaskermolen-5-edam/',
    'https://rcmakelaars.nl/woningen/willem-runderkampstraat-20-volendam/',
    'https://rcmakelaars.nl/woningen/schoklandstraat-67-volendam/',
    'https://rcmakelaars.nl/woningen/nieuwvaartje-10-edam/',
    'https://rcmakelaars.nl/woningen/kleine-kerkstraat-10-edam/',
    'https://rcmakelaars.nl/woningen/gouden-slot-53-volendam/',
    'https://rcmakelaars.nl/woningen/damcoogh-2-volendam/',
    'https://rcmakelaars.nl/woningen/st-gerardusstraat-3-volendam/',
    'https://rcmakelaars.nl/woningen/gouden-slot-11-volendam/',
];
